### ISSUE TITLE
Apocalypse now bear trap

### ISSUE THREAD

**Issue by MaximTaranenko** [TqLxQuanZ/DeceasedCraft#21]
I might have found a bug, bear trap from apocalypse now deals damage even if its closed. Because of this it is absolutely OP, since it deals huge damage per second and stops target from moving at all. Nothing comes close, spikes and wires deal x3-x5 less damage and at the very best slows.

**Comment by TheOneDal** [comment]
I brought this up with the apocalypse now dev a while ago, the massive amount of damage the trap deals is not intended and will be fixed in the next release. 
As for the trap dealing damage while closed, 
"I think i may come with a solution, i can take away the block effects after a while, but for like 10 seconds the trap will be function even if its close"
I interpret this as it wont deal damage again after the initial trigger until it resets itself but you will still get stuck on it.
