### ISSUE TITLE
Drill heads disappearing 

### ISSUE THREAD

**Issue by cyco20** [TqLxQuanZ/DeceasedCraft#29]
Sometimes, the head of the drill from immersive engineering and its attachments tend to phase out of reality? I don't know how to describe it. The model and description still have all the items I added, but they are not there when I put the drill on the table. 
![Screenshot 2024-02-27 212854](https://github.com/TqLxQuanZ/DeceasedCraft/assets/78839527/8b3765f5-24b1-44a6-be47-e2d41f2ba105)
![Screenshot 2024-02-27 212953](https://github.com/TqLxQuanZ/DeceasedCraft/assets/78839527/3a484af3-6d98-48b1-81fe-9ca54ae143e7)
![Screenshot 2024-02-27 213146](https://github.com/TqLxQuanZ/DeceasedCraft/assets/78839527/2d431680-370c-4e92-b11d-61304674358c)

**Comment by TqLxQuanZ** [comment]
Test it out with immersive engineering alone, if the bug exists then it's their mod problem and I am pretty sure they aren't updating 1.18.2 anymore, so there's no fix for that.
Otherwise if it still works fine with the mod alone, then there's some other mod conflict which I do not know at all conflicting the immersive engineering drill.
