### ISSUE TITLE
port numbers are overwritten in server.properties

### ISSUE THREAD

**Issue by McKitten** [TqLxQuanZ/DeceasedCraft#40]
I set the server up with a custom world name, specific port and whitelisting on, just for something else to overwrite them and the server be unusable because the port is wrong.

I am hoping its that default properties file doing it?

**Comment by TheOneDal** [comment]
uh are you not setting that stuff up through the default properties files?
Where are you setting this if not?

**Comment by TheOneDal** [comment]
ignore last comment, i realize you ment the "default properties file".
I hope your not changing the settings while the server is running? I spent like 30min with some guy who did that.
Are you locally hosting or using some server hosting site.

**Comment by TqLxQuanZ** [comment]
default properties only setup once and it will no longer setup the server properties anymore, and there shouldn't be any mod overwriting it other than that, you might want to do a few more time test especially if the server is ongoing and you modify the server port.
Otherwise, there is probably another server using that port.
